
server:
  port: 8763 # 8761是eureka server的默认端口
eureka:
  server:
    enable-self-preservation: true #防止由于Eureka的机制导致Client被错误显示在线 仅在开发环境使用
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/, http://localhost:8761/eureka/ #这便是此eureka server的应用注册地址
    register-with-eureka: true #表示是否将自己注册到Eureka Server上，默认为true
    fetch-registry: true       #表示是否从Eureka Server上获取注册信息，默认为true
spring:
  application:
    name: lz-eureka-server