

##客户端端口号
server:
  port: 8181

spring:
  application:        #服务名称
    name: client-01
  redis:              #连接redis配置
    host: localhost
    port: 6379
    database: 1       #指定连接的redis库
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/


